version: '3'

services:
  db:
    container_name: db
    build:
       dockerfile: Dockerfile
       context: ./mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MY_SQL_ROOT_PASSWORD: wordpress
      MY_SQL_USER: wordpress
      MY_SQL_PASSWORD: wordpress
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - inception

  wordpress:
    depends_on:
      - db
    container_name: wordpress
    build:
       dockerfile: Dockerfile
       context: ./wordpress
    ports:
      - "9000:80"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  nginx:
    depends_on:
      - wordpress
      - db
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

networks:
  inception:

volumes:
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: '/home/tlemesle/data/wordpress'
  dbdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: '/home/tlemesle/data/mariadb'